
services:
  postgres:
    image: postgres:latest
    container_name: calorie_calculator_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calorie_calculator
    ports:
      - "5432:5432"

